### ISSUE TITLE
Invalid component definition on frontend when using vue-svg-loader

### ISSUE THREAD

**Issue by leeuwd** [storybooks/vue-cli-plugin-storybook#10]
<img width="478" alt="schermafbeelding 2018-08-13 om 09 03 21" src="https://user-images.githubusercontent.com/1755190/44017212-ca627c96-9ed7-11e8-95db-7eef1f126562.png">

Occurs with `storybook/vue@4.0.0-alpha.16` and [`vue-svg-loader@0.5.0`](https://github.com/visualfanatic/vue-svg-loader). To get the Vue SVG loader working with Vue CLI 3 (`3.0.0-rc.12`), I have this in `vue.config.js`:

```js
chainWebpack: (config) => {
    const svgRule = config.module.rule('svg');

    svgRule.uses.clear();

    svgRule
      .oneOf('inline')
      .resourceQuery(/inline/)
      .use('vue-svg-loader')
      .loader('vue-svg-loader')
      .end()
      .end()
      .oneOf('external')
      .use('file-loader')
      .loader('file-loader')
      .options({ name: 'assets/[name].[hash:8].[ext]' });
  },
```

**Comment by pksunkara** [comment]
@leeuwd I have never worked with SVG in vue, and I am currently having trouble rendering the SVG using `npm run serve` even with the webpack config you provided. Would you be willing to make a small reproduction project for this issue? As soon as I can reproduce this, I will be able to fix it.

**Comment by leeuwd** [comment]
@pksunkara: here you go, https://github.com/leeuwd/svg-issue-demo

**Comment by pksunkara** [comment]
Confirmed that able to reproduce this.

**Comment by pksunkara** [comment]
Can confirm it is an issue of `api.resolveWebpackConfig();`. Vue is probably not loading `vue.config.js` at this point.

**Comment by pksunkara** [comment]
Thanks for helping improve this. This should be fixed now in 0.4.3

**Comment by SwannLV** [comment]
@leeuwd Hello, have you found how to get this working?

Thanks a lot

**Comment by pksunkara** [comment]
@SwannLV What are you having issue with?
