### ISSUE TITLE
build:storybook fails when "extract css" is enable

### ISSUE THREAD

**Issue by tonimc** [storybooks/vue-cli-plugin-storybook#12]
## DESCRIPTION
The build step fails when the project has css-extract activated.

## ERROR
Webpack fails because is not able to load the `mini-css-extract-plugin`

## STEPS TO REPRODUCE
1. `vue create test-story-build`
2. `cd test-story-build`
3. `vue add storybook`
4. Set extract css to true in `vue.config.js`
`module.exports = {
  css: {
    extract: true
  }
}`
5. `yarn run build:storybook`

**Comment by pksunkara** [comment]
@tonimc I think I now fixed this. You should be good to go. If you found any more issues, don't hesitate to create an issue. Since, this is an official plugin from @storybooks/team, we are always looking to be perfect.

**Comment by ndelangen** [comment]
How does the `extract: true` work? What does it do?

I fixed a related thing here:
https://github.com/storybooks/storybook/pull/4134

**Comment by pksunkara** [comment]
Good fix. Probably fixes something broken which wasn't reported. This issue was more about this plugin removing extract-css plugin from vue webpack config which is being used for storybook webpack config.

**Comment by ndelangen** [comment]
Well extracting css in storybook isn't recommended (you loose HMR), but now it's supported.

**Comment by tonimc** [comment]
@ndelangen the problem didn't come by extract CSS in the storybook, the problem comes because a user wants to extract CSS in his Vue component and as Storybook for Vue uses the project's webpack config, it fails when starts/build storybook (dev or production mode, now fixed).

So If extracting css is not recomended in storybook, maybe the plugin should omit the extract css config in the storybook project.
