### ISSUE TITLE
0.4.8 not published

### ISSUE THREAD

**Issue by gabemule** [storybooks/vue-cli-plugin-storybook#24]
Hi @pksunkara , noticed that version 0.4.8 has been tagged but never published in npm!
Thanks!!! =)

**Comment by haakseth** [comment]
Tip 🔥: While you wait for it to be published to npm, you can add it to your project directly from github like this: 

```yarn add --dev git+https://git@github.com/storybooks/vue-cli-plugin-storybook```

... or the npm equivalent

**Comment by pksunkara** [comment]
I have removed the tag guys because I realized it's not the correct way to fix things. I am working on fixing the whole thing with a new 0.5.0 release. Thanks for your patience.

**Comment by pksunkara** [comment]
I realized that I need to add a lot more tests to get 0.5.0. So, I am releasing 0.4.8 in the meanwhile.
