### ISSUE TITLE
Vue component that imports mixin crashes

### ISSUE THREAD

**Issue by DirkStevens** [storybooks/vue-cli-plugin-storybook#34]
Created a new Vue CLI 3 project
`vue create demo`

In the `demo` folder
`vue add storybook`

Run storybook - works nicely
`npm run serve:storybook`

Added mixin MyMixin.js in the `src/components` folder:
![image](https://user-images.githubusercontent.com/1837524/46622461-ff793a80-cb2a-11e8-9aab-50e80c304e6e.png)

Added references to mixin in `src/components/MyButton.vue`
![image](https://user-images.githubusercontent.com/1837524/46622490-1c157280-cb2b-11e8-985f-89abd0846910.png)

Storybook crashes:
`ERROR in ./src/components/MyButton.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MyButton.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'MyMixin.js' in '/Users/madewith/MadeWith/demo/src/components'
 @ ./src/components/MyButton.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MyButton.vue?vue&type=script&lang=js&) 7:0-33
 @ ./src/components/MyButton.vue?vue&type=script&lang=js&
 @ ./src/components/MyButton.vue
 @ ./src/stories/index.stories.js
 @ ./src/stories sync .stories.js$
 @ ./config/storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./config/storybook/config.js (webpack)-hot-middleware/client.js?reload=true
ℹ ｢wdm｣: Failed to compile.`

**Comment by backbone87** [comment]
invalid. your IDE even points you to your syntax mistake within the mixin file

**Comment by pksunkara** [comment]
Can you give me a valid example?

**Comment by backbone87** [comment]
i am going to close because no response and the error seems unrelated to storybook or this plugin, feel free to reopen
