### ISSUE TITLE
vue-cli webpack config not fully copied ?

### ISSUE THREAD

**Issue by rndmerle** [storybooks/vue-cli-plugin-storybook#37]
Hi.

in vue.config.js I've among other stuff:
```
performance: { hints: false },
resolve: { alias: { '~': path.resolve(__dirname) } },
```
**It seems none of those are copied in the configuration for Storybook** because 1) I get the performance messages and 2) I get errors like `Module not found: Error: Can't resolve '~/config' in ...`

If I create a Storybook's webpack.config.js and add those properties than it's working fine.

_@vue/cli-service 3.1.1_
_vue-cli-plugin-storybook 0.4.8_

**Comment by pksunkara** [comment]
I am not sure. @rndmerle Can you test it again?

**Comment by backbone87** [comment]
the resolve works for me, i tested it with the default vue cli 3 '@' alias

**Comment by rndmerle** [comment]
Yea default @ alias is working. What's not copied it seems are custom `configureWebpack` properties from vue.config.js
Here is a repo for reproduction: https://github.com/rndmerle/repro-vue-cli-plugin-storybook

Points of interest:
- "~" alias configured in vue.config.js and tsconfig.js. 
- hints:false in vue.config.js
- MyButton.vue is imported with "~" alias from HelloWorld.vue and from index.stories.js

Reproduction:
- Run `serve`: app is working and MyButton is imported
- Run `storybook:build`: presence of performance hint message and `Can't resolve '~/src/components/MyButton.vue'` error
