### ISSUE TITLE
Lint command in generator does not lint /storybook directory

### ISSUE THREAD

**Issue by nickforddesign** [storybooks/vue-cli-plugin-storybook#43]
After installing, the generator runs the vue cli lint service. However, it only lint the default vue directories, /src and /tests, it does not lint /storybook.

I'm currently trying to solve this problem for my own unrelated CLI plugin, so I'm very interesting to see any ideas. If I come up with anything I will comment here as well.

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-eslint/lint.js#L39

**Comment by nickforddesign** [comment]
Just got a reply about this from @LinusBorg

https://forum.vuejs.org/t/lint-entire-project/54797

**Comment by backbone87** [comment]
yeah the lint command is a pretty naive impl on vue's side and they never react to PRs in time. i wanted to change the way it detects what to lint, like default tslint does, but they never reply to issues or accept PRs, so whatever
