### ISSUE TITLE
Plugin filtering issue

### ISSUE THREAD

**Issue by nickforddesign** [storybooks/vue-cli-plugin-storybook#44]
Readme says all plugins included via `configureWebpack` will not be filtered, but given the following vue.config.js:

```js
/* eslint-disable import/no-extraneous-dependencies */
const path = require('path');
const webpack = require('webpack');

module.exports = {
  lintOnSave: 'error',
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      }),
      new webpack.EnvironmentPlugin({
        TESTING: 'test 123'
      })
    ]
  }
};
```

`process.env.TESTING` is undefined in storybook, but working in my Vue app. The mapbox plugin is also undefined.

**Comment by pksunkara** [comment]
I am not sure about the environment plugin. https://github.com/storybooks/vue-cli-plugin-storybook/issues/16

But the other plugin should be there though. https://github.com/storybooks/vue-cli-plugin-storybook/pull/42. /cc @jimvandervoort

**Comment by nickforddesign** [comment]
@pksunkara Oh I see what's happening, you merged in that PR but haven't published the update to npm yet. I just tried to update the plugin but the changes aren't there yet.

Can you publish the new update please? Thanks!

**Comment by pksunkara** [comment]
Released. Could you check if this works now?

**Comment by nickforddesign** [comment]
🎉 That fixed both problems! Thank you so much!
