### ISSUE TITLE
On 0.5.1 and 0.5.2, serve storybook generates a webpack error

### ISSUE THREAD

**Issue by rperello** [storybooks/vue-cli-plugin-storybook#48]
Thanks for your work

Error trace:

ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.plugins[9] should be one of these:
ERR!    object { apply, … } | function
ERR!    -> Plugin of type object or instanceof Function
ERR!    Details:
ERR!     * configuration.plugins[9] should be an object.
ERR!       -> Plugin instance
ERR!     * configuration.plugins[9] should be an instance of function
ERR!       -> Function acting as plugin
ERR!     at webpack (/Users/rperello/Developer/web_components/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at _default (/Users/rperello/Developer/web_components/node_modules/@storybook/core/dist/server/dev-server.js:92:47)
ERR!     at process.internalTickCallback (internal/process/next_tick.js:77:7)
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.plugins[9] should be one of these:
ERR!    object { apply, … } | function
ERR!    -> Plugin of type object or instanceof Function
ERR!    Details:
ERR!     * configuration.plugins[9] should be an object.
ERR!       -> Plugin instance
ERR!     * configuration.plugins[9] should be an instance of function
ERR!       -> Function acting as plugin
ERR!     at webpack (/Users/rperello/Developer/web_components/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at _default (/Users/rperello/Developer/web_components/node_modules/@storybook/core/dist/server/dev-server.js:92:47)
ERR!     at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by pksunkara** [comment]
What was your setup?

**Comment by pksunkara** [comment]
Any update on this? I will close this soon if none.

**Comment by rperello** [comment]
A vue inspect will be enough info?

**Comment by pksunkara** [comment]
Maybe. But let's start with that

**Comment by rperello** [comment]
Ok, on monday i will send It.

**Comment by rperello** [comment]
Close it. Now show another error.
