### ISSUE TITLE
Storybook 5

### ISSUE THREAD

**Issue by jsilva-pt** [storybooks/vue-cli-plugin-storybook#52]
Hello :)

I was just trying to update my project to the last version of Storybook and found out that the support was added only in master branch.

Any plan to release this?

Until ther I'm using master branch directly:
`"vue-cli-plugin-storybook": "storybooks/vue-cli-plugin-storybook#master",`

**Comment by pksunkara** [comment]
Plugin version 0.6.0 with storybook 5 is now published

**Comment by jsilva-pt** [comment]
Thanks ;)
