### ISSUE TITLE
what is advantage of installing this over installing @storybook/vue directly?

### ISSUE THREAD

**Issue by vesper8** [storybooks/vue-cli-plugin-storybook#58]
Sorry if this is obvious but I'm having a hard time understanding why someone should use this as opposed to installing and configuring @storybook/vue without the use of this plugin.. what advantage or conveniences does using the plugin provide? Rather, what are the pros and cons?

Thank you

**Comment by elevatebart** [comment]
This will do most of the config for you.
It will create a `.storybook` directory, set up the necessary plugins so that you re immediately ready to go. If you already are using `@storybook/vue` it might be an unnecessary step.

Does this help?

**Comment by vesper8** [comment]
yes thank you..

I received an unusual error when I tried adding the plugin

```
Installing vue-cli-plugin-storybook...

npm ERR! Unexpected end of JSON input while parsing near '..."chalk":"^2.0.1","com'
```

So I ended up adding it manually to my package.json, which installed it but did not do this auto-configuration you speak of

So I ended up removing it and installing `@storybook/vue` directly and settings up the config and folders manually.. a bit more tedious but I got it working

**Comment by backbone87** [comment]
the generator (default setup etc) is only run if you install the package via vue-cli.
