### ISSUE TITLE
Make this official & become of storybook collaborator 

### ISSUE THREAD

**Issue by ndelangen** [storybooks/vue-cli-plugin-storybook#9]
Hey @pksunkara 

OW man wow, this is so awesome! I should have googled before tweeting! https://twitter.com/NorbertdeLangen/status/1028197030349484037

Would you feel good about moving this to the storybook organisation on github and becoming a maintainer there? (offer extends to all collaborators here)

♥️ storybook team

**Comment by pksunkara** [comment]
Would love to. Have been reading storybook code a lot for this plugin. What are the steps? I accepted your invitation to @storybooks.

**Comment by pksunkara** [comment]
Also, I would need this to make the plugin not install all the extra babel stuff. https://github.com/storybooks/storybook/pull/3746#issuecomment-412143536

**Comment by ndelangen** [comment]
@pksunkara I'm so happy! You should be allowed to move this repo to the organisation now.

I will work on the babel PR monday, should get merged.

What more do you need, really open to discussing changes to facilitate this more.
@igor-dv has been working on presets in Storybook (he's working on typescript) so users can tweak the workings and configs by installing packages, instead of changing config files!

**Comment by pksunkara** [comment]
Transferred the repository on github. What about NPM?

Regarding other issues, I had to write my own custom `@storybook/vue/server` code for this at [here](https://github.com/storybooks/vue-cli-plugin-storybook/blob/master/index.js#L13). I might not have completely understood how storybook works, so, would appreciate a small look at that part.

Also, do you guys hangout somewhere to chat regarding storybook development?

**Comment by igor-dv** [comment]
We have a [slack](https://now-examples-slackin-nqnzoygycp.now.sh/) =)

**Comment by pksunkara** [comment]
Added both of you on NPM. Will add other people when they contribute. Closing this issue since this is official now.

**Comment by ndelangen** [comment]
🥇
